'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { 
  User, 
  MapPin, 
  Phone, 
  Mail, 
  Calendar, 
  Star, 
  Briefcase, 
  Award, 
  Edit3, 
  Save, 
  X, 
  CheckCircle, 
  Clock, 
  Shield, 
  Camera, 
  Upload,
  Settings,
  LogOut,
  Eye,
  EyeOff,
  FileText,
  MessageSquare,
  TrendingUp,
  Users,
  DollarSign,
  Globe
} from 'lucide-react'
import { ImageUpload } from '@/components/ImageUpload'
import { supabase } from '@/lib/supabase'
import { validateField as validateFieldUtil, validateForm as validateFormUtil } from '@/lib/validation'
import { VALIDATION_RULES } from '@/lib/constants'

interface ProfileData {
  id: string
  name: string
  profession: string
  category: string
  email: string
  phone: string
  location: string
  experience: number
  rating: number
  description: string
  services: string[]
  availability: string
  imageUrl?: string
  verified: boolean
  createdAt: string
  website?: string
  socialLinks?: {
    linkedin?: string
    twitter?: string
    facebook?: string
    instagram?: string
  }
  pricing?: {
    hourlyRate?: number
    serviceTypes?: string[]
  }
  stats?: {
    jobsCompleted: number
    repeatClients: number
    responseRate: number
    avgResponseTime: string
  }
  updated_at?: string
}

type UpdateData = Omit<ProfileData, 'id' | 'createdAt' | 'rating' | 'verified' | 'stats'>

export default function MyProfilePage() {
  const router = useRouter()
  const [user, setUser] = useState<any>(null)
  const [profile, setProfile] = useState<ProfileData | null>(null)
  const [loading, setLoading] = useState(true)
  const [editing, setEditing] = useState(false)
  const [saving, setSaving] = useState(false)
  const [formData, setFormData] = useState<Partial<ProfileData>>({})
  const [originalData, setOriginalData] = useState<Partial<ProfileData>>({})
  const [newService, setNewService] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [hasChanges, setHasChanges] = useState(false)
  const [savingStatus, setSavingStatus] = useState<'idle' | 'saving' | 'success' | 'error'>('idle')

  useEffect(() => {
    const checkAuth = async () => {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session) {
        router.push('/auth/signin')
        return
      }
      setUser(session.user)
      if (session.user.email) {
        fetchProfile(session.user.email)
      }
    }

    checkAuth()
  }, [router])

  const fetchProfile = async (userEmail: string) => {
    try {
      const { data, error } = await supabase
        .from('professionals')
        .select('*')
        .eq('email', userEmail)
        .single()

      if (error && error.code !== 'PGRST116') {
        console.error('Error fetching profile:', error)
        setLoading(false)
        return
      }

      if (data) {
        setProfile(data as ProfileData)
        setFormData(data as ProfileData)
      } else {
        // Create default profile if none exists
        const { data: { session: currentSession } } = await supabase.auth.getSession()
        const defaultProfile: Partial<ProfileData> = {
          id: '', // Will be generated by database
          name: currentSession?.user?.user_metadata?.full_name || currentSession?.user?.email?.split('@')[0] || '',
          profession: '',
          category: 'other',
          email: userEmail,
          phone: '',
          location: '',
          experience: 0,
          rating: 0,
          description: '',
          services: [],
          availability: '',
          verified: false,
          createdAt: new Date().toISOString(),
          website: '',
          socialLinks: {},
          pricing: {
            hourlyRate: 0,
            serviceTypes: []
          },
          stats: {
            jobsCompleted: 0,
            repeatClients: 0,
            responseRate: 95,
            avgResponseTime: '2 hours'
          }
        }
        setProfile(defaultProfile as ProfileData)
        setFormData(defaultProfile)
      }
    } catch (error) {
      console.error('Error:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleSave = async () => {
    setSaving(true)
    setSavingStatus('saving')
    
    try {
      // Validate form first
      if (!validateForm()) {
        setSavingStatus('error')
        setSaving(false)
        return
      }

      const profileData = {
        name: formData.name || '',
        profession: formData.profession || '',
        category: formData.category || 'other',
        email: formData.email || '',
        phone: formData.phone || '',
        location: formData.location || '',
        experience: formData.experience || 0,
        description: formData.description || '',
        services: formData.services || [],
        availability: formData.availability || '',
        imageUrl: formData.imageUrl,
        website: formData.website,
        socialLinks: formData.socialLinks,
        pricing: formData.pricing,
        updated_at: new Date().toISOString()
      }

      // Use insert or update based on whether profile exists
      if (profile) {
        const { error } = await (supabase
          .from('professionals')
          // @ts-ignore
          .update(profileData)
          .eq('email', user?.email))

        if (error) {
          console.error('Error updating profile:', error)
          setSavingStatus('error')
          setSaving(false)
          return
        }
      } else {
        const { error } = await (supabase
          .from('professionals')
          // @ts-ignore
          .insert({ ...profileData, email: user?.email }))

        if (error) {
          console.error('Error creating profile:', error)
          setSavingStatus('error')
          setSaving(false)
          return
        }
      }

      setProfile(formData as ProfileData)
      setOriginalData({ ...formData })
      setHasChanges(false)
      setEditing(false)
      setSavingStatus('success')
      
      // Show success message
      setTimeout(() => {
        setSavingStatus('idle')
      }, 2000)
    } catch (error) {
      console.error('Error:', error)
      setSavingStatus('error')
    } finally {
      setSaving(false)
    }
  }

  const handleSignOut = async () => {
    await supabase.auth.signOut()
    router.push('/')
  }

  const validateForm = (): boolean => {
    const result = validateFormUtil(formData)
    setErrors(result.errors)
    return result.isValid
  }

  const startEditing = () => {
    setOriginalData({ ...formData })
    setErrors({})
    setHasChanges(false)
    setEditing(true)
    setSavingStatus('idle')
  }

  const cancelEditing = () => {
    setFormData({ ...originalData })
    setErrors({})
    setHasChanges(false)
    setEditing(false)
    setSavingStatus('idle')
  }

  const handleFieldChange = (field: keyof ProfileData, value: any) => {
    setFormData({ ...formData, [field]: value })
    
    // Clear error for this field when user starts typing
    if (errors[field]) {
      setErrors({ ...errors, [field]: '' })
    }
    
    // Check if there are changes
    const hasFieldChanged = JSON.stringify(formData[field]) !== JSON.stringify(originalData[field])
    setHasChanges(hasFieldChanged || (Object.keys(formData) as Array<keyof ProfileData>).some(key => 
      JSON.stringify(formData[key]) !== JSON.stringify(originalData[key])
    ))
  }

  const addService = () => {
    if (newService.trim() && formData.services) {
      setFormData({
        ...formData,
        services: [...formData.services, newService.trim()]
      })
      setNewService('')
    }
  }

  const removeService = (index: number) => {
    if (formData.services) {
      setFormData({
        ...formData,
        services: formData.services.filter((_, i) => i !== index)
      })
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading profile...</p>
        </div>
      </div>
    )
  }

  if (!profile) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Profile Not Found</h2>
          <p className="text-gray-600 mb-4">Please create your profile to get started.</p>
          <Link href="/add-profile">
            <Button>Create Profile</Button>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 shadow-sm">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="text-gray-600 hover:text-gray-900">
              <Button variant="ghost" size="sm">
                ← Back to Directory
              </Button>
            </Link>
            <div className="flex items-center gap-4">
              {profile?.id && (
                <Link href={`/profile/${profile.id}`}>
                  <Button variant="outline" size="sm">
                    <Eye className="h-4 w-4 mr-2" />
                    View Public Profile
                  </Button>
                </Link>
              )}
              <Button variant="outline" size="sm" onClick={handleSignOut}>
                <LogOut className="h-4 w-4 mr-2" />
                Sign Out
              </Button>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        {!editing ? (
          <>
            {/* View Mode - Original Layout */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <div className="lg:col-span-2 space-y-6">
              {/* Profile Header */}
              <Card>
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div className="flex items-center gap-6">
                      {/* Profile Image */}
                      <div className="relative">
                        <div className="w-24 h-24 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-full flex items-center justify-center">
                          {profile.imageUrl ? (
                            <img 
                              src={profile.imageUrl} 
                              alt={profile.name}
                              className="w-full h-full rounded-full object-cover"
                            />
                          ) : (
                            <User className="h-12 w-12 text-white" />
                          )}
                        </div>
                      </div>
                      
                      {/* Basic Info */}
                      <div className="flex-1">
                        <div>
                          <h1 className="text-2xl font-bold text-gray-900">{profile.name}</h1>
                          <p className="text-lg text-gray-600">{profile.profession}</p>
                        </div>
                        
                        {/* Stats */}
                        <div className="flex items-center gap-4 mt-3">
                          <div className="flex items-center gap-1">
                            <Star className="h-5 w-5 fill-yellow-400 text-yellow-400" />
                            <span className="font-semibold">{profile.rating || 'N/A'}</span>
                          </div>
                          {profile.verified && (
                            <div className="flex items-center gap-1 text-green-600">
                              <CheckCircle className="h-5 w-5" />
                              <span className="font-medium">Verified</span>
                            </div>
                          )}
                          <Badge variant="outline" className="capitalize">
                            {profile.category}
                          </Badge>
                        </div>
                      </div>
                    </div>
                    
                    {/* Action Buttons */}
                    <Button onClick={startEditing}>
                      <Edit3 className="h-4 w-4 mr-2" />
                      Edit Profile
                    </Button>
                  </div>
                </CardHeader>
              </Card>

              {/* About Section */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <FileText className="h-5 w-5" />
                    About
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-700 leading-relaxed">
                    {profile.description || 'No description provided yet.'}
                  </p>
                </CardContent>
              </Card>

              {/* Services Section */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Briefcase className="h-5 w-5" />
                    Services Offered
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2">
                    {profile.services?.map((service, index) => (
                      <Badge key={index} variant="secondary">
                        {service}
                      </Badge>
                    ))}
                    {(!profile.services || profile.services.length === 0) && (
                      <p className="text-gray-500">No services listed yet.</p>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Contact Information */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Phone className="h-5 w-5" />
                    Contact Information
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div className="flex items-center gap-3">
                    <Mail className="h-5 w-5 text-gray-400" />
                    <span>{profile.email}</span>
                  </div>
                  {profile.phone && (
                    <div className="flex items-center gap-3">
                      <Phone className="h-5 w-5 text-gray-400" />
                      <span>{profile.phone}</span>
                    </div>
                  )}
                  {profile.location && (
                    <div className="flex items-center gap-3">
                      <MapPin className="h-5 w-5 text-gray-400" />
                      <span>{profile.location}</span>
                    </div>
                  )}
                  {profile.availability && (
                    <div className="flex items-center gap-3">
                      <Clock className="h-5 w-5 text-gray-400" />
                      <span>{profile.availability}</span>
                    </div>
                  )}
                  {profile.website && (
                    <div className="flex items-center gap-3">
                      <Globe className="h-5 w-5 text-gray-400" />
                      <a href={profile.website} target="_blank" rel="noopener noreferrer" className="text-indigo-600 hover:underline">
                        {profile.website}
                      </a>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          </div>
        ) : (
          // Edit Mode - Clean Form Layout
          <div className="max-w-3xl mx-auto space-y-6">
            {/* Status Messages */}
            {savingStatus === 'success' && (
              <div className="flex items-center gap-2 text-green-600 text-sm bg-green-50 p-3 rounded-lg border border-green-200">
                <CheckCircle className="h-4 w-4" />
                Profile saved successfully!
              </div>
            )}
            {savingStatus === 'error' && (
              <div className="flex items-center gap-2 text-red-600 text-sm bg-red-50 p-3 rounded-lg border border-red-200">
                <X className="h-4 w-4" />
                Failed to save profile. Please check your inputs.
              </div>
            )}

            {/* Basic Information Section */}
            <Card className="bg-white border border-gray-200 shadow-sm">
              <CardHeader className="border-b border-gray-200 bg-gray-50">
                <CardTitle className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                  <User className="h-5 w-5 text-indigo-600" />
                  Basic Information
                </CardTitle>
                <p className="text-sm text-gray-600 mt-1">Update your profile details</p>
              </CardHeader>
              <CardContent className="p-6 space-y-6">
                {/* Profile Photo */}
                <div>
                  <Label className="text-sm font-medium text-gray-900">Profile Photo</Label>
                  <p className="text-xs text-gray-500 mt-1 mb-3">Upload a professional photo</p>
                  <div className="mt-2">
                    <ImageUpload
                      currentImage={formData.imageUrl}
                      onImageChange={(url) => handleFieldChange('imageUrl', url || undefined)}
                      className="max-w-xs mx-auto"
                    />
                  </div>
                </div>

                {/* Name and Profession */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="name" className="text-sm font-medium text-gray-900">Full Name <span className="text-red-500">*</span></Label>
                    <Input
                      id="name"
                      value={formData.name || ''}
                      onChange={(e) => handleFieldChange('name', e.target.value)}
                      placeholder="Enter your full name"
                      className={`mt-2 h-11 border-gray-300 rounded-lg ${errors.name ? 'border-red-500' : ''}`}
                    />
                    {errors.name && <p className="text-sm text-red-600 mt-1.5">{errors.name}</p>}
                  </div>
                  <div>
                    <Label htmlFor="profession" className="text-sm font-medium text-gray-900">Profession <span className="text-red-500">*</span></Label>
                    <Input
                      id="profession"
                      value={formData.profession || ''}
                      onChange={(e) => handleFieldChange('profession', e.target.value)}
                      placeholder="e.g., Software Engineer, Plumber"
                      className={`mt-2 h-11 border-gray-300 rounded-lg ${errors.profession ? 'border-red-500' : ''}`}
                    />
                    {errors.profession && <p className="text-sm text-red-600 mt-1.5">{errors.profession}</p>}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* About Section */}
            <Card className="bg-white border border-gray-200 shadow-sm">
              <CardHeader className="border-b border-gray-200 bg-gray-50">
                <CardTitle className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                  <FileText className="h-5 w-5 text-indigo-600" />
                  About
                </CardTitle>
                <p className="text-sm text-gray-600 mt-1">Describe your professional background</p>
              </CardHeader>
              <CardContent className="p-6">
                <Textarea
                  value={formData.description || ''}
                  onChange={(e) => handleFieldChange('description', e.target.value)}
                  placeholder="Tell us about yourself, your experience, and what makes you unique..."
                  rows={5}
                  className="border-gray-300 rounded-lg resize-none"
                />
              </CardContent>
            </Card>

            {/* Services Section */}
            <Card className="bg-white border border-gray-200 shadow-sm">
              <CardHeader className="border-b border-gray-200 bg-gray-50">
                <CardTitle className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                  <Briefcase className="h-5 w-5 text-indigo-600" />
                  Services Offered
                </CardTitle>
                <p className="text-sm text-gray-600 mt-1">List the services you provide</p>
              </CardHeader>
              <CardContent className="p-6 space-y-4">
                <div className="flex gap-2">
                  <Input
                    value={newService}
                    onChange={(e) => setNewService(e.target.value)}
                    placeholder="Add a service..."
                    onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), addService())}
                    className="h-11 border-gray-300 rounded-lg"
                  />
                  <Button onClick={addService} className="bg-indigo-600 hover:bg-indigo-700 text-white">
                    <Briefcase className="h-4 w-4 mr-2" />
                    Add
                  </Button>
                </div>
                {formData.services && formData.services.length > 0 && (
                  <div className="flex flex-wrap gap-2 p-3 bg-gray-50 rounded-lg border border-gray-200">
                    {formData.services.map((service, index) => (
                      <Badge key={index} variant="secondary" className="pr-1 bg-white border-gray-300 text-gray-700 hover:bg-gray-50">
                        {service}
                        <button
                          type="button"
                          onClick={() => removeService(index)}
                          className="ml-2 hover:text-red-600 transition-colors"
                          aria-label={`Remove ${service}`}
                        >
                          <X className="h-3 w-3" />
                        </button>
                      </Badge>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Contact Information Section */}
            <Card className="bg-white border border-gray-200 shadow-sm">
              <CardHeader className="border-b border-gray-200 bg-gray-50">
                <CardTitle className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                  <Phone className="h-5 w-5 text-indigo-600" />
                  Contact Information
                </CardTitle>
                <p className="text-sm text-gray-600 mt-1">How clients can reach you</p>
              </CardHeader>
              <CardContent className="p-6 space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="email" className="text-sm font-medium text-gray-900 flex items-center gap-2">
                      <Mail className="h-4 w-4 text-gray-500" />
                      Email <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      id="email"
                      type="email"
                      value={formData.email || ''}
                      onChange={(e) => handleFieldChange('email', e.target.value)}
                      className="mt-2 h-11 border-gray-300 rounded-lg"
                    />
                  </div>
                  <div>
                    <Label htmlFor="phone" className="text-sm font-medium text-gray-900 flex items-center gap-2">
                      <Phone className="h-4 w-4 text-gray-500" />
                      Phone <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      id="phone"
                      type="tel"
                      value={formData.phone || ''}
                      onChange={(e) => handleFieldChange('phone', e.target.value)}
                      placeholder="e.g., +1 (555) 123-4567"
                      className="mt-2 h-11 border-gray-300 rounded-lg"
                    />
                  </div>
                  <div>
                    <Label htmlFor="location" className="text-sm font-medium text-gray-900 flex items-center gap-2">
                      <MapPin className="h-4 w-4 text-gray-500" />
                      Location <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      id="location"
                      value={formData.location || ''}
                      onChange={(e) => handleFieldChange('location', e.target.value)}
                      placeholder="City, State"
                      className="mt-2 h-11 border-gray-300 rounded-lg"
                    />
                  </div>
                  <div>
                    <Label htmlFor="availability" className="text-sm font-medium text-gray-900 flex items-center gap-2">
                      <Clock className="h-4 w-4 text-gray-500" />
                      Availability <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      id="availability"
                      value={formData.availability || ''}
                      onChange={(e) => handleFieldChange('availability', e.target.value)}
                      placeholder="e.g., Mon-Fri: 9AM-5PM"
                      className="mt-2 h-11 border-gray-300 rounded-lg"
                    />
                  </div>
                </div>
                <div>
                  <Label htmlFor="website" className="text-sm font-medium text-gray-900 flex items-center gap-2">
                    <Globe className="h-4 w-4 text-gray-500" />
                    Website
                  </Label>
                  <Input
                    id="website"
                    type="url"
                    value={formData.website || ''}
                    onChange={(e) => handleFieldChange('website', e.target.value)}
                    placeholder="https://yourwebsite.com"
                    className="mt-2 h-11 border-gray-300 rounded-lg"
                  />
                </div>
              </CardContent>
            </Card>

            {/* Action Buttons */}
            <div className="flex flex-col sm:flex-row gap-4 items-center justify-between pt-4 bg-white p-6 rounded-lg border border-gray-200">
              <p className="text-sm text-gray-600">
                <span className="text-red-500">*</span> Required fields
              </p>
              <div className="flex gap-3">
                <Button 
                  variant="outline" 
                  onClick={cancelEditing}
                  disabled={saving}
                  className="border-gray-300"
                >
                  <X className="h-4 w-4 mr-2" />
                  Cancel
                </Button>
                <Button 
                  onClick={handleSave} 
                  disabled={saving || !hasChanges}
                  className="bg-indigo-600 hover:bg-indigo-700 text-white min-w-[150px]"
                >
                  {saving ? (
                    <>
                      <span className="animate-spin mr-2">⏳</span>
                      Saving...
                    </>
                  ) : (
                    <>
                      <Save className="h-4 w-4 mr-2" />
                      Save Changes
                    </>
                  )}
                </Button>
              </div>
            </div>

            {/* Sidebar */}
            <div className="space-y-6">
            {/* Profile Completion */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Profile Completion</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-gray-600">Overall</span>
                    <span className="text-sm font-semibold">75%</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2">
                    <div className="bg-indigo-600 h-2 rounded-full" style={{ width: '75%' }}></div>
                  </div>
                  <div className="space-y-2 text-sm">
                    <div className="flex items-center gap-2">
                      <CheckCircle className="h-4 w-4 text-green-500" />
                      <span>Basic Info</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckCircle className="h-4 w-4 text-green-500" />
                      <span>Contact Details</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="h-4 w-4 border-2 border-gray-300 rounded-full"></div>
                      <span>Services</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="h-4 w-4 border-2 border-gray-300 rounded-full"></div>
                      <span>Portfolio</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Quick Stats */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Performance Stats</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Briefcase className="h-4 w-4 text-gray-400" />
                    <span className="text-sm">Jobs Completed</span>
                  </div>
                  <span className="font-semibold">{profile.stats?.jobsCompleted || 0}</span>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Users className="h-4 w-4 text-gray-400" />
                    <span className="text-sm">Repeat Clients</span>
                  </div>
                  <span className="font-semibold">{profile.stats?.repeatClients || 0}</span>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <MessageSquare className="h-4 w-4 text-gray-400" />
                    <span className="text-sm">Response Rate</span>
                  </div>
                  <span className="font-semibold">{profile.stats?.responseRate || 95}%</span>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4 text-gray-400" />
                    <span className="text-sm">Avg Response</span>
                  </div>
                  <span className="font-semibold">{profile.stats?.avgResponseTime || '2 hours'}</span>
                </div>
              </CardContent>
            </Card>

            {/* Verification Status */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Verification Status</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-sm">Email Verified</span>
                  <CheckCircle className="h-4 w-4 text-green-500" />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm">Phone Verified</span>
                  {profile.verified ? (
                    <CheckCircle className="h-4 w-4 text-green-500" />
                  ) : (
                    <div className="h-4 w-4 border-2 border-gray-300 rounded-full"></div>
                  )}
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm">Background Check</span>
                  {profile.verified ? (
                    <CheckCircle className="h-4 w-4 text-green-500" />
                  ) : (
                    <div className="h-4 w-4 border-2 border-gray-300 rounded-full"></div>
                  )}
                </div>
                <Button variant="outline" size="sm" className="w-full mt-4">
                  <Shield className="h-4 w-4 mr-2" />
                  Get Verified
                </Button>
              </CardContent>
            </Card>

            {/* Quick Actions */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Quick Actions</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <Link href="/settings">
                  <Button variant="outline" size="sm" className="w-full">
                    <Settings className="h-4 w-4 mr-2" />
                    Account Settings
                  </Button>
                </Link>
                <Button variant="outline" size="sm" className="w-full" disabled>
                  <TrendingUp className="h-4 w-4 mr-2" />
                  View Analytics
                  <span className="ml-2 text-xs text-gray-400">(Coming Soon)</span>
                </Button>
                <Button variant="outline" size="sm" className="w-full" disabled>
                  <MessageSquare className="h-4 w-4 mr-2" />
                  Messages
                  <span className="ml-2 text-xs text-gray-400">(Coming Soon)</span>
                </Button>
              </CardContent>
            </Card>
          </div>
          </div>
          </>
        ) : (
          <>
            {/* Edit Mode - Clean Form Layout */}
            <div className="max-w-3xl mx-auto space-y-6">
            {/* Status Messages */}
            {savingStatus === 'success' && (
              <div className="flex items-center gap-2 text-green-600 text-sm bg-green-50 p-3 rounded-lg border border-green-200">
                <CheckCircle className="h-4 w-4" />
                Profile saved successfully!
              </div>
            )}
            {savingStatus === 'error' && (
              <div className="flex items-center gap-2 text-red-600 text-sm bg-red-50 p-3 rounded-lg border border-red-200">
                <X className="h-4 w-4" />
                Failed to save profile. Please check your inputs.
              </div>
            )}

            {/* Basic Information Section */}
            <Card className="bg-white border border-gray-200 shadow-sm">
              <CardHeader className="border-b border-gray-200 bg-gray-50">
                <CardTitle className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                  <User className="h-5 w-5 text-indigo-600" />
                  Basic Information
                </CardTitle>
                <p className="text-sm text-gray-600 mt-1">Update your profile details</p>
              </CardHeader>
              <CardContent className="p-6 space-y-6">
                {/* Profile Photo */}
                <div>
                  <Label className="text-sm font-medium text-gray-900">Profile Photo</Label>
                  <p className="text-xs text-gray-500 mt-1 mb-3">Upload a professional photo</p>
                  <div className="mt-2">
                    <ImageUpload
                      currentImage={formData.imageUrl}
                      onImageChange={(url) => handleFieldChange('imageUrl', url || undefined)}
                      className="max-w-xs mx-auto"
                    />
                  </div>
                </div>

                {/* Name and Profession */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="name" className="text-sm font-medium text-gray-900">Full Name <span className="text-red-500">*</span></Label>
                    <Input
                      id="name"
                      value={formData.name || ''}
                      onChange={(e) => handleFieldChange('name', e.target.value)}
                      placeholder="Enter your full name"
                      className={`mt-2 h-11 border-gray-300 rounded-lg ${errors.name ? 'border-red-500' : ''}`}
                    />
                    {errors.name && <p className="text-sm text-red-600 mt-1.5">{errors.name}</p>}
                  </div>
                  <div>
                    <Label htmlFor="profession" className="text-sm font-medium text-gray-900">Profession <span className="text-red-500">*</span></Label>
                    <Input
                      id="profession"
                      value={formData.profession || ''}
                      onChange={(e) => handleFieldChange('profession', e.target.value)}
                      placeholder="e.g., Software Engineer, Plumber"
                      className={`mt-2 h-11 border-gray-300 rounded-lg ${errors.profession ? 'border-red-500' : ''}`}
                    />
                    {errors.profession && <p className="text-sm text-red-600 mt-1.5">{errors.profession}</p>}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* About Section */}
            <Card className="bg-white border border-gray-200 shadow-sm">
              <CardHeader className="border-b border-gray-200 bg-gray-50">
                <CardTitle className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                  <FileText className="h-5 w-5 text-indigo-600" />
                  About
                </CardTitle>
                <p className="text-sm text-gray-600 mt-1">Describe your professional background</p>
              </CardHeader>
              <CardContent className="p-6">
                <Textarea
                  value={formData.description || ''}
                  onChange={(e) => handleFieldChange('description', e.target.value)}
                  placeholder="Tell us about yourself, your experience, and what makes you unique..."
                  rows={5}
                  className="border-gray-300 rounded-lg resize-none"
                />
              </CardContent>
            </Card>

            {/* Services Section */}
            <Card className="bg-white border border-gray-200 shadow-sm">
              <CardHeader className="border-b border-gray-200 bg-gray-50">
                <CardTitle className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                  <Briefcase className="h-5 w-5 text-indigo-600" />
                  Services Offered
                </CardTitle>
                <p className="text-sm text-gray-600 mt-1">List the services you provide</p>
              </CardHeader>
              <CardContent className="p-6 space-y-4">
                <div className="flex gap-2">
                  <Input
                    value={newService}
                    onChange={(e) => setNewService(e.target.value)}
                    placeholder="Add a service..."
                    onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), addService())}
                    className="h-11 border-gray-300 rounded-lg"
                  />
                  <Button onClick={addService} className="bg-indigo-600 hover:bg-indigo-700 text-white">
                    <Briefcase className="h-4 w-4 mr-2" />
                    Add
                  </Button>
                </div>
                {formData.services && formData.services.length > 0 && (
                  <div className="flex flex-wrap gap-2 p-3 bg-gray-50 rounded-lg border border-gray-200">
                    {formData.services.map((service, index) => (
                      <Badge key={index} variant="secondary" className="pr-1 bg-white border-gray-300 text-gray-700 hover:bg-gray-50">
                        {service}
                        <button
                          type="button"
                          onClick={() => removeService(index)}
                          className="ml-2 hover:text-red-600 transition-colors"
                          aria-label={`Remove ${service}`}
                        >
                          <X className="h-3 w-3" />
                        </button>
                      </Badge>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Contact Information Section */}
            <Card className="bg-white border border-gray-200 shadow-sm">
              <CardHeader className="border-b border-gray-200 bg-gray-50">
                <CardTitle className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                  <Phone className="h-5 w-5 text-indigo-600" />
                  Contact Information
                </CardTitle>
                <p className="text-sm text-gray-600 mt-1">How clients can reach you</p>
              </CardHeader>
              <CardContent className="p-6 space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="email" className="text-sm font-medium text-gray-900 flex items-center gap-2">
                      <Mail className="h-4 w-4 text-gray-500" />
                      Email <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      id="email"
                      type="email"
                      value={formData.email || ''}
                      onChange={(e) => handleFieldChange('email', e.target.value)}
                      className="mt-2 h-11 border-gray-300 rounded-lg"
                    />
                  </div>
                  <div>
                    <Label htmlFor="phone" className="text-sm font-medium text-gray-900 flex items-center gap-2">
                      <Phone className="h-4 w-4 text-gray-500" />
                      Phone <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      id="phone"
                      type="tel"
                      value={formData.phone || ''}
                      onChange={(e) => handleFieldChange('phone', e.target.value)}
                      placeholder="e.g., +1 (555) 123-4567"
                      className="mt-2 h-11 border-gray-300 rounded-lg"
                    />
                  </div>
                  <div>
                    <Label htmlFor="location" className="text-sm font-medium text-gray-900 flex items-center gap-2">
                      <MapPin className="h-4 w-4 text-gray-500" />
                      Location <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      id="location"
                      value={formData.location || ''}
                      onChange={(e) => handleFieldChange('location', e.target.value)}
                      placeholder="City, State"
                      className="mt-2 h-11 border-gray-300 rounded-lg"
                    />
                  </div>
                  <div>
                    <Label htmlFor="availability" className="text-sm font-medium text-gray-900 flex items-center gap-2">
                      <Clock className="h-4 w-4 text-gray-500" />
                      Availability <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      id="availability"
                      value={formData.availability || ''}
                      onChange={(e) => handleFieldChange('availability', e.target.value)}
                      placeholder="e.g., Mon-Fri: 9AM-5PM"
                      className="mt-2 h-11 border-gray-300 rounded-lg"
                    />
                  </div>
                </div>
                <div>
                  <Label htmlFor="website" className="text-sm font-medium text-gray-900 flex items-center gap-2">
                    <Globe className="h-4 w-4 text-gray-500" />
                    Website
                  </Label>
                  <Input
                    id="website"
                    type="url"
                    value={formData.website || ''}
                    onChange={(e) => handleFieldChange('website', e.target.value)}
                    placeholder="https://yourwebsite.com"
                    className="mt-2 h-11 border-gray-300 rounded-lg"
                  />
                </div>
              </CardContent>
            </Card>

            {/* Action Buttons */}
            <div className="flex flex-col sm:flex-row gap-4 items-center justify-between pt-4 bg-white p-6 rounded-lg border border-gray-200">
              <p className="text-sm text-gray-600">
                <span className="text-red-500">*</span> Required fields
              </p>
              <div className="flex gap-3">
                <Button 
                  variant="outline" 
                  onClick={cancelEditing}
                  disabled={saving}
                  className="border-gray-300"
                >
                  <X className="h-4 w-4 mr-2" />
                  Cancel
                </Button>
                <Button 
                  onClick={handleSave} 
                  disabled={saving || !hasChanges}
                  className="bg-indigo-600 hover:bg-indigo-700 text-white min-w-[150px]"
                >
                  {saving ? (
                    <>
                      <span className="animate-spin mr-2">⏳</span>
                      Saving...
                    </>
                  ) : (
                    <>
                      <Save className="h-4 w-4 mr-2" />
                      Save Changes
                    </>
                  )}
                </Button>
              </div>
            </div>
          </div>
          </>
        )}
      </div>
    </div>
  )
}
